# Generated by Django 3.2.5 on 2021-07-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ManyToManyField(blank=True, to='notes.Category'),
        ),
    ]
