# Generated by Django 3.2.5 on 2021-07-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_author'),
        ('notes', '0005_rename_category_note_categories'),
    ]

    operations = [
    ]
