# Generated by Django 3.2.6 on 2021-08-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_note_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='full_path',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
