# Generated by Django 3.2.6 on 2021-08-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_auto_20210818_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
