# Generated by Django 3.2.6 on 2021-08-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_add_note_status_and_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
