# Generated by Django 3.2.6 on 2021-08-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_delete_bulletpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
