# Generated by Django 3.2.6 on 2021-09-07 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0022_alter_note_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shareditem',
            unique_together={('note', 'user')},
        ),
    ]
