# Generated by Django 3.2.8 on 2021-11-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0023_alter_shareditem_unique_together'),
        ('notes', '0025_alter_comment_creation_date'),
    ]

    operations = [
    ]
