# Generated by Django 4.0.3 on 2022-04-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0027_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
